version: '3.1'

services:
    postgres:
      image: postgres:9.6.17-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: pgadmin999
        POSTGRES_USER: root
        POSTGRES_DB: ideas
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
    api:
      build: .
      container_name: api
      restart: always
      environment:
        DB_URL: "host=postgres user=root password=pgadmin999 dbname=ideas port=5432 sslmode=disable"
      ports:
        - "8080:8080"
    pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
