name: publish_backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./backend/api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            nullchannel/null-web-backend:latest
    